const data = {
  success: "true",
  data: {
    youtube: {
      items: [
        {
          id: {
            kind: "youtube#video",
            videoId: "nLRL_NcnK-4",
          },
          snippet: {
            title:
              "Harvard CS50’s Introduction to Programming with Python – Full University Course",
            channelTitle: "freeCodeCamp.org",
          },
        },
        {
          id: {
            kind: "youtube#video",
            videoId: "x7X9w_GIm1s",
          },
          snippet: {
            title: "Python in 100 Seconds",
            channelTitle: "Fireship",
          },
        },
        {
          id: {
            kind: "youtube#video",
            videoId: "_uQrJ0TkZlc",
          },
          snippet: {
            title: "Python Tutorial - Python Full Course for Beginners",
            channelTitle: "Programming with Mosh",
          },
        },
        {
          id: {
            kind: "youtube#playlist",
            playlistId: "PLu0W_9lII9agwh1XjRt242xIpHhPT2llg",
          },
          snippet: {
            title:
              "Python for Beginners (Full Course) | #100DaysOfCode Programming Tutorial in Hindi",
            channelTitle: "CodeWithHarry",
          },
        },
        {
          id: {
            kind: "youtube#video",
            videoId: "rfscVS0vtbw",
          },
          snippet: {
            title: "Learn Python - Full Course for Beginners [Tutorial]",
            channelTitle: "freeCodeCamp.org",
          },
        },
        {
          id: {
            kind: "youtube#video",
            videoId: "kqtD5dpn9C8",
          },
          snippet: {
            title: "Python for Beginners - Learn Python in 1 Hour",
            channelTitle: "Programming with Mosh",
          },
        },
        {
          id: {
            kind: "youtube#video",
            videoId: "m67-bOpOoPU",
          },
          snippet: {
            title:
              "Python Tutorial - Python Full Course for Beginners in Tamil",
            channelTitle: "Error Makes Clever Academy",
          },
        },
        {
          id: {
            kind: "youtube#video",
            videoId: "XKHEtdqhLK8",
          },
          snippet: {
            title: "Python Full Course for free 🐍",
            channelTitle: "Bro Code",
          },
        },
        {
          id: {
            kind: "youtube#video",
            videoId: "jnZatfMc6rM",
          },
          snippet: {
            title:
              "Devcontainers en localhost + automatizando tareas repetitivas con Python",
            channelTitle: "Python Colombia",
          },
        },
        {
          id: {
            kind: "youtube#video",
            videoId: "vLqTf2b6GZw",
          },
          snippet: {
            title: "Python Tutorial for Beginners | Learn Python in 1.5 Hours",
            channelTitle: "Apna College",
          },
        },
      ],
    },
    reddit: {
      kind: "Listing",
      data: {
        modhash: null,
        dist: 5,
        facets: {},
        after: "t3_ztlduy",
        geo_filter: "",
        children: [
          {
            kind: "t3",
            data: {
              approved_at_utc: null,
              subreddit: "ProgrammerHumor",
              selftext: "",
              author_fullname: "t2_48ukj4i3",
              saved: false,
              mod_reason_title: null,
              gilded: 0,
              clicked: false,
              title: "STOP USING PYTHON 😡😡😡",
              link_flair_richtext: [
                {
                  e: "text",
                  t: "Meme",
                },
              ],
              subreddit_name_prefixed: "r/ProgrammerHumor",
              hidden: false,
              pwls: 6,
              link_flair_css_class: "meme",
              downs: 0,
              thumbnail_height: 140,
              top_awarded_type: null,
              hide_score: false,
              name: "t3_13rqbgz",
              quarantine: false,
              link_flair_text_color: "light",
              upvote_ratio: 0.94,
              author_flair_background_color: null,
              ups: 6901,
              total_awards_received: 0,
              media_embed: {},
              thumbnail_width: 140,
              author_flair_template_id: null,
              is_original_content: false,
              user_reports: [],
              secure_media: null,
              is_reddit_media_domain: true,
              is_meta: false,
              category: null,
              secure_media_embed: {},
              link_flair_text: "Meme",
              can_mod_post: false,
              score: 6901,
              approved_by: null,
              is_created_from_ads_ui: false,
              author_premium: false,
              thumbnail:
                "https://b.thumbs.redditmedia.com/qGbMbI8LA2wWEmMOX7RGzc472nWJWxfYRAL7IipDuyg.jpg",
              edited: false,
              author_flair_css_class: null,
              author_flair_richtext: [],
              gildings: {},
              post_hint: "image",
              content_categories: null,
              is_self: false,
              subreddit_type: "public",
              created: 1685041589.0,
              link_flair_type: "richtext",
              wls: 6,
              removed_by_category: null,
              banned_by: null,
              author_flair_type: "text",
              domain: "i.redd.it",
              allow_live_comments: true,
              selftext_html: null,
              likes: null,
              suggested_sort: null,
              banned_at_utc: null,
              url_overridden_by_dest: "https://i.redd.it/yo7dbdorh22b1.jpg",
              view_count: null,
              archived: false,
              no_follow: false,
              is_crosspostable: true,
              pinned: false,
              over_18: false,
              preview: {
                images: [
                  {
                    source: {
                      url: "https://preview.redd.it/yo7dbdorh22b1.jpg?auto=webp&amp;s=b6b34882b02cd4cede8e09762ee35dcfa627561b",
                      width: 1200,
                      height: 1200,
                    },
                    resolutions: [
                      {
                        url: "https://preview.redd.it/yo7dbdorh22b1.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=b5f449bbe4fa2ef85b7a47764b8edefddace8629",
                        width: 108,
                        height: 108,
                      },
                      {
                        url: "https://preview.redd.it/yo7dbdorh22b1.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=8cc200dd6cf9adebe704eb09bfa5db221da824d0",
                        width: 216,
                        height: 216,
                      },
                      {
                        url: "https://preview.redd.it/yo7dbdorh22b1.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=6a7aef507fcf49cb00f36a6b95a00f5dc9378440",
                        width: 320,
                        height: 320,
                      },
                      {
                        url: "https://preview.redd.it/yo7dbdorh22b1.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=b611c991a3219abd631d59d958db9561f2abcf8d",
                        width: 640,
                        height: 640,
                      },
                      {
                        url: "https://preview.redd.it/yo7dbdorh22b1.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=65b5790ec64348edd44bd72674c7e33b2f2cda8b",
                        width: 960,
                        height: 960,
                      },
                      {
                        url: "https://preview.redd.it/yo7dbdorh22b1.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=30e43ab800d99553fce68044a2e122d7cd310547",
                        width: 1080,
                        height: 1080,
                      },
                    ],
                    variants: {},
                    id: "5zoLUZFV_esuH1kZx5xJLLhmTfQMKZC2PWSaV9AorR0",
                  },
                ],
                enabled: true,
              },
              all_awardings: [],
              awarders: [],
              media_only: false,
              link_flair_template_id: "fe277d42-440f-11e8-8ec3-0eac434afc94",
              can_gild: false,
              spoiler: false,
              locked: false,
              author_flair_text: null,
              treatment_tags: [],
              visited: false,
              removed_by: null,
              mod_note: null,
              distinguished: null,
              subreddit_id: "t5_2tex6",
              author_is_blocked: false,
              mod_reason_by: null,
              num_reports: null,
              removal_reason: null,
              link_flair_background_color: "#373c3f",
              id: "13rqbgz",
              is_robot_indexable: true,
              report_reasons: null,
              author: "C-O-S-M-O",
              discussion_type: null,
              num_comments: 230,
              send_replies: true,
              whitelist_status: "all_ads",
              contest_mode: false,
              mod_reports: [],
              author_patreon_flair: false,
              author_flair_text_color: null,
              permalink:
                "/r/ProgrammerHumor/comments/13rqbgz/stop_using_python/",
              parent_whitelist_status: "all_ads",
              stickied: false,
              url: "https://i.redd.it/yo7dbdorh22b1.jpg",
              subreddit_subscribers: 3154052,
              created_utc: 1685041589.0,
              num_crossposts: 3,
              media: null,
              is_video: false,
            },
          },
          {
            kind: "t3",
            data: {
              approved_at_utc: null,
              subreddit: "ProgrammerHumor",
              selftext: "",
              author_fullname: "t2_moxsta",
              saved: false,
              mod_reason_title: null,
              gilded: 1,
              clicked: false,
              title: "C++ talking to Python",
              link_flair_richtext: [],
              subreddit_name_prefixed: "r/ProgrammerHumor",
              hidden: false,
              pwls: 6,
              link_flair_css_class: null,
              downs: 0,
              thumbnail_height: 140,
              top_awarded_type: null,
              hide_score: false,
              name: "t3_w1upl0",
              quarantine: false,
              link_flair_text_color: "dark",
              upvote_ratio: 0.87,
              author_flair_background_color: null,
              subreddit_type: "public",
              ups: 40081,
              total_awards_received: 0,
              media_embed: {},
              thumbnail_width: 140,
              author_flair_template_id: null,
              is_original_content: false,
              user_reports: [],
              secure_media: null,
              is_reddit_media_domain: true,
              is_meta: false,
              category: null,
              secure_media_embed: {},
              link_flair_text: null,
              can_mod_post: false,
              score: 40081,
              approved_by: null,
              is_created_from_ads_ui: false,
              author_premium: false,
              thumbnail:
                "https://b.thumbs.redditmedia.com/p1xlfGsgYQ9Hl-VMdDIMWWB-Z5dFtd6xbFE2cyF53nU.jpg",
              edited: false,
              author_flair_css_class: null,
              author_flair_richtext: [],
              gildings: {},
              post_hint: "image",
              content_categories: null,
              is_self: false,
              mod_note: null,
              created: 1658135273.0,
              link_flair_type: "text",
              wls: 6,
              removed_by_category: null,
              banned_by: null,
              author_flair_type: "text",
              domain: "i.redd.it",
              allow_live_comments: true,
              selftext_html: null,
              likes: null,
              suggested_sort: null,
              banned_at_utc: null,
              url_overridden_by_dest: "https://i.redd.it/40t7alhvlac91.png",
              view_count: null,
              archived: true,
              no_follow: false,
              is_crosspostable: true,
              pinned: false,
              over_18: false,
              preview: {
                images: [
                  {
                    source: {
                      url: "https://preview.redd.it/40t7alhvlac91.png?auto=webp&amp;s=53b8e28ef788a84771a3a847252c2ec0130cf419",
                      width: 1422,
                      height: 1510,
                    },
                    resolutions: [
                      {
                        url: "https://preview.redd.it/40t7alhvlac91.png?width=108&amp;crop=smart&amp;auto=webp&amp;s=27b30bef33503caa5c32439c5b3c7601466eea37",
                        width: 108,
                        height: 114,
                      },
                      {
                        url: "https://preview.redd.it/40t7alhvlac91.png?width=216&amp;crop=smart&amp;auto=webp&amp;s=9aafb38d025f1167e1d40f13603f3574c0e25431",
                        width: 216,
                        height: 229,
                      },
                      {
                        url: "https://preview.redd.it/40t7alhvlac91.png?width=320&amp;crop=smart&amp;auto=webp&amp;s=99bcf8c6caf7e15ccd225921ef048759c3329525",
                        width: 320,
                        height: 339,
                      },
                      {
                        url: "https://preview.redd.it/40t7alhvlac91.png?width=640&amp;crop=smart&amp;auto=webp&amp;s=a4f43ec5249731149ec64cbcf09d002a47e711fd",
                        width: 640,
                        height: 679,
                      },
                      {
                        url: "https://preview.redd.it/40t7alhvlac91.png?width=960&amp;crop=smart&amp;auto=webp&amp;s=5ccb8b9f46fbe4abb0f2c8822800722947a4737f",
                        width: 960,
                        height: 1019,
                      },
                      {
                        url: "https://preview.redd.it/40t7alhvlac91.png?width=1080&amp;crop=smart&amp;auto=webp&amp;s=935f254436057a1fbc2a854094b5f7cb79a20419",
                        width: 1080,
                        height: 1146,
                      },
                    ],
                    variants: {},
                    id: "lOhbaEYkt9Yzgg9WaWIoM06LE45yM1ZPVdisGw-6KKI",
                  },
                ],
                enabled: true,
              },
              all_awardings: [],
              awarders: [],
              media_only: false,
              can_gild: false,
              spoiler: false,
              locked: false,
              author_flair_text: null,
              treatment_tags: [],
              visited: false,
              removed_by: null,
              num_reports: null,
              distinguished: null,
              subreddit_id: "t5_2tex6",
              author_is_blocked: false,
              mod_reason_by: null,
              removal_reason: null,
              link_flair_background_color: "",
              id: "w1upl0",
              is_robot_indexable: true,
              report_reasons: null,
              author: "b98765",
              discussion_type: null,
              num_comments: 1054,
              send_replies: true,
              whitelist_status: "all_ads",
              contest_mode: false,
              mod_reports: [],
              author_patreon_flair: false,
              author_flair_text_color: null,
              permalink:
                "/r/ProgrammerHumor/comments/w1upl0/c_talking_to_python/",
              parent_whitelist_status: "all_ads",
              stickied: false,
              url: "https://i.redd.it/40t7alhvlac91.png",
              subreddit_subscribers: 3154052,
              created_utc: 1658135273.0,
              num_crossposts: 4,
              media: null,
              is_video: false,
            },
          },
          {
            kind: "t3",
            data: {
              approved_at_utc: null,
              subreddit: "ChatGPT",
              selftext:
                "i had the idea to ask chatgpt to set up a study plan for me to learn python, within 6 months. It set up a daily learning plan, asks me questions, tells me whats wrong with my code, gives me resources to learn and also clarifies any doubts i have, its like the best personal tuitor u could ask for. You can ask it to design a study plan according to ur uni classes and syllabus and it will do so. Its basically everything i can ask for.",
              author_fullname: "t2_l9gjwx30",
              saved: false,
              mod_reason_title: null,
              gilded: 1,
              clicked: false,
              title: "i use chatgpt to learn python",
              link_flair_richtext: [
                {
                  e: "text",
                  t: "Educational Purpose Only ",
                },
              ],
              subreddit_name_prefixed: "r/ChatGPT",
              hidden: false,
              pwls: 6,
              link_flair_css_class: "",
              downs: 0,
              thumbnail_height: null,
              top_awarded_type: null,
              hide_score: false,
              name: "t3_13xcy1j",
              quarantine: false,
              link_flair_text_color: "dark",
              upvote_ratio: 0.93,
              author_flair_background_color: null,
              subreddit_type: "public",
              ups: 7025,
              total_awards_received: 0,
              media_embed: {},
              thumbnail_width: null,
              author_flair_template_id: null,
              is_original_content: false,
              user_reports: [],
              secure_media: null,
              is_reddit_media_domain: false,
              is_meta: false,
              category: null,
              secure_media_embed: {},
              link_flair_text: "Educational Purpose Only ",
              can_mod_post: false,
              score: 7025,
              approved_by: null,
              is_created_from_ads_ui: false,
              author_premium: false,
              thumbnail: "self",
              edited: false,
              author_flair_css_class: null,
              author_flair_richtext: [],
              gildings: {},
              content_categories: null,
              is_self: true,
              mod_note: null,
              created: 1685611737.0,
              link_flair_type: "richtext",
              wls: 6,
              removed_by_category: null,
              banned_by: null,
              author_flair_type: "text",
              domain: "self.ChatGPT",
              allow_live_comments: true,
              selftext_html:
                '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;i had the idea to ask chatgpt to set up a study plan for me to learn python, within 6 months. It set up a daily learning plan, asks me questions, tells me whats wrong with my code, gives me resources to learn and also clarifies any doubts i have, its like the best personal tuitor u could ask for. You can ask it to design a study plan according to ur uni classes and syllabus and it will do so. Its basically everything i can ask for.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
              likes: null,
              suggested_sort: null,
              banned_at_utc: null,
              view_count: null,
              archived: false,
              no_follow: false,
              is_crosspostable: true,
              pinned: false,
              over_18: false,
              all_awardings: [],
              awarders: [],
              media_only: false,
              link_flair_template_id: "26e7b998-7bbc-11ed-ba93-22ce55064b6a",
              can_gild: false,
              spoiler: false,
              locked: false,
              author_flair_text: null,
              treatment_tags: [],
              visited: false,
              removed_by: null,
              num_reports: null,
              distinguished: null,
              subreddit_id: "t5_7hqomg",
              author_is_blocked: false,
              mod_reason_by: null,
              removal_reason: null,
              link_flair_background_color: "#0079d3",
              id: "13xcy1j",
              is_robot_indexable: true,
              report_reasons: null,
              author: "Clinnkk_",
              discussion_type: null,
              num_comments: 643,
              send_replies: true,
              whitelist_status: "all_ads",
              contest_mode: false,
              mod_reports: [],
              author_patreon_flair: false,
              author_flair_text_color: null,
              permalink:
                "/r/ChatGPT/comments/13xcy1j/i_use_chatgpt_to_learn_python/",
              parent_whitelist_status: "all_ads",
              stickied: false,
              url: "https://www.reddit.com/r/ChatGPT/comments/13xcy1j/i_use_chatgpt_to_learn_python/",
              subreddit_subscribers: 3210603,
              created_utc: 1685611737.0,
              num_crossposts: 7,
              media: null,
              is_video: false,
            },
          },
          {
            kind: "t3",
            data: {
              approved_at_utc: null,
              subreddit: "excel",
              selftext:
                "After years of waiting for an update from the Microsoft Excel team, it looks like python for Excel is now in preview:\n\nhttps://techcommunity.microsoft.com/t5/excel-blog/announcing-python-in-excel-combining-the-power-of-python-and-the/ba-p/3893439",
              author_fullname: "t2_4zpyk",
              saved: false,
              mod_reason_title: null,
              gilded: 0,
              clicked: false,
              title:
                "Announcing Python in Excel: Combining the power of Python and the flexibility of Excel.",
              link_flair_richtext: [
                {
                  e: "text",
                  t: "Discussion",
                },
              ],
              subreddit_name_prefixed: "r/excel",
              hidden: false,
              pwls: 6,
              link_flair_css_class: "discussioncase",
              downs: 0,
              thumbnail_height: null,
              top_awarded_type: null,
              hide_score: false,
              name: "t3_15y5voc",
              quarantine: false,
              link_flair_text_color: "light",
              upvote_ratio: 0.99,
              author_flair_background_color: "#008e00",
              subreddit_type: "public",
              ups: 345,
              total_awards_received: 0,
              media_embed: {},
              thumbnail_width: null,
              author_flair_template_id: "29c92406-6c36-11e9-969e-0e508a31bef4",
              is_original_content: false,
              user_reports: [],
              secure_media: null,
              is_reddit_media_domain: false,
              is_meta: false,
              category: null,
              secure_media_embed: {},
              link_flair_text: "Discussion",
              can_mod_post: false,
              score: 345,
              approved_by: null,
              is_created_from_ads_ui: false,
              author_premium: false,
              thumbnail: "self",
              edited: 1692712048.0,
              author_flair_css_class: "points",
              author_flair_richtext: [
                {
                  e: "text",
                  t: "48",
                },
              ],
              gildings: {},
              post_hint: "self",
              content_categories: null,
              is_self: true,
              mod_note: null,
              created: 1692710930.0,
              link_flair_type: "richtext",
              wls: 6,
              removed_by_category: null,
              banned_by: null,
              author_flair_type: "richtext",
              domain: "self.excel",
              allow_live_comments: false,
              selftext_html:
                '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;After years of waiting for an update from the Microsoft Excel team, it looks like python for Excel is now in preview:&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://techcommunity.microsoft.com/t5/excel-blog/announcing-python-in-excel-combining-the-power-of-python-and-the/ba-p/3893439"&gt;https://techcommunity.microsoft.com/t5/excel-blog/announcing-python-in-excel-combining-the-power-of-python-and-the/ba-p/3893439&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
              likes: null,
              suggested_sort: "top",
              banned_at_utc: null,
              view_count: null,
              archived: false,
              no_follow: false,
              is_crosspostable: true,
              pinned: false,
              over_18: false,
              preview: {
                images: [
                  {
                    source: {
                      url: "https://external-preview.redd.it/UgFfFi6TEzGVbDgnDrd1HHWFgYUywpMCJR47hgYMWzM.jpg?auto=webp&amp;s=a90f7862fdbe9d5a78b8b7daa2caa1f60d244520",
                      width: 999,
                      height: 562,
                    },
                    resolutions: [
                      {
                        url: "https://external-preview.redd.it/UgFfFi6TEzGVbDgnDrd1HHWFgYUywpMCJR47hgYMWzM.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=87c97dad07b61bcbf92769ac734af5688999dd40",
                        width: 108,
                        height: 60,
                      },
                      {
                        url: "https://external-preview.redd.it/UgFfFi6TEzGVbDgnDrd1HHWFgYUywpMCJR47hgYMWzM.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=0d66d763e48a11b273eab52788cb4c5d03eb4ce4",
                        width: 216,
                        height: 121,
                      },
                      {
                        url: "https://external-preview.redd.it/UgFfFi6TEzGVbDgnDrd1HHWFgYUywpMCJR47hgYMWzM.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=45e3f88b214277306aaa3a3798c814c979570d8d",
                        width: 320,
                        height: 180,
                      },
                      {
                        url: "https://external-preview.redd.it/UgFfFi6TEzGVbDgnDrd1HHWFgYUywpMCJR47hgYMWzM.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=673eba04a35efa177455af30e538ed46012fbbe5",
                        width: 640,
                        height: 360,
                      },
                      {
                        url: "https://external-preview.redd.it/UgFfFi6TEzGVbDgnDrd1HHWFgYUywpMCJR47hgYMWzM.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=6920bc45e78cb7b5dbf218670e6cf78515f77fae",
                        width: 960,
                        height: 540,
                      },
                    ],
                    variants: {},
                    id: "Uz1arDxus1ALe0fiVEJBejwjdC_XPbK6f8adnJjqtck",
                  },
                ],
                enabled: false,
              },
              all_awardings: [],
              awarders: [],
              media_only: false,
              link_flair_template_id: "382b7fda-d516-11e1-8b86-12313b088941",
              can_gild: false,
              spoiler: false,
              locked: false,
              author_flair_text: "48",
              treatment_tags: [],
              visited: false,
              removed_by: null,
              num_reports: null,
              distinguished: null,
              subreddit_id: "t5_2qur2",
              author_is_blocked: false,
              mod_reason_by: null,
              removal_reason: null,
              link_flair_background_color: "#768ba7",
              id: "15y5voc",
              is_robot_indexable: true,
              report_reasons: null,
              author: "beyphy",
              discussion_type: null,
              num_comments: 115,
              send_replies: true,
              whitelist_status: "all_ads",
              contest_mode: false,
              mod_reports: [],
              author_patreon_flair: false,
              author_flair_text_color: "light",
              permalink:
                "/r/excel/comments/15y5voc/announcing_python_in_excel_combining_the_power_of/",
              parent_whitelist_status: "all_ads",
              stickied: false,
              url: "https://www.reddit.com/r/excel/comments/15y5voc/announcing_python_in_excel_combining_the_power_of/",
              subreddit_subscribers: 636669,
              created_utc: 1692710930.0,
              num_crossposts: 1,
              media: null,
              is_video: false,
            },
          },
          {
            kind: "t3",
            data: {
              approved_at_utc: null,
              subreddit: "ProgrammerHumor",
              selftext: "",
              author_fullname: "t2_38hhmg35",
              saved: false,
              mod_reason_title: null,
              gilded: 0,
              clicked: false,
              title: 'Python programmers be like: "Yeah that makes sense" 🤔',
              link_flair_richtext: [
                {
                  e: "text",
                  t: "Meme",
                },
              ],
              subreddit_name_prefixed: "r/ProgrammerHumor",
              hidden: false,
              pwls: 6,
              link_flair_css_class: "meme",
              downs: 0,
              thumbnail_height: 38,
              top_awarded_type: null,
              hide_score: false,
              name: "t3_ztlduy",
              quarantine: false,
              link_flair_text_color: "light",
              upvote_ratio: 0.94,
              author_flair_background_color: "transparent",
              ups: 33822,
              total_awards_received: 0,
              media_embed: {},
              thumbnail_width: 140,
              author_flair_template_id: "2fe60290-008a-11e9-ba3a-0edd34b083f8",
              is_original_content: false,
              user_reports: [],
              secure_media: null,
              is_reddit_media_domain: true,
              is_meta: false,
              category: null,
              secure_media_embed: {},
              link_flair_text: "Meme",
              can_mod_post: false,
              score: 33822,
              approved_by: null,
              is_created_from_ads_ui: false,
              author_premium: false,
              thumbnail:
                "https://a.thumbs.redditmedia.com/wXMDPwXDufbm5GpuOV1PCc0h8X_hberDfIYmXWC3y34.jpg",
              edited: false,
              author_flair_css_class: null,
              author_flair_richtext: [
                {
                  a: ":py:",
                  e: "emoji",
                  u: "https://emoji.redditmedia.com/u2ijjhenzg421_t5_2tex6/py",
                },
              ],
              gildings: {},
              post_hint: "image",
              content_categories: null,
              is_self: false,
              subreddit_type: "public",
              created: 1671812796.0,
              link_flair_type: "richtext",
              wls: 6,
              removed_by_category: null,
              banned_by: null,
              author_flair_type: "richtext",
              domain: "i.redd.it",
              allow_live_comments: true,
              selftext_html: null,
              likes: null,
              suggested_sort: null,
              banned_at_utc: null,
              url_overridden_by_dest: "https://i.redd.it/c5r01v03co7a1.jpg",
              view_count: null,
              archived: true,
              no_follow: false,
              is_crosspostable: true,
              pinned: false,
              over_18: false,
              preview: {
                images: [
                  {
                    source: {
                      url: "https://preview.redd.it/c5r01v03co7a1.jpg?auto=webp&amp;s=3925d3381741e1ff055b649315cd04ea5e1cfb5b",
                      width: 953,
                      height: 262,
                    },
                    resolutions: [
                      {
                        url: "https://preview.redd.it/c5r01v03co7a1.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=29fba6fd962f132b4a31a7f4d066fff3d93fc867",
                        width: 108,
                        height: 29,
                      },
                      {
                        url: "https://preview.redd.it/c5r01v03co7a1.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=29203ac690fced0de38a8d3dcea95808c0282b20",
                        width: 216,
                        height: 59,
                      },
                      {
                        url: "https://preview.redd.it/c5r01v03co7a1.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=04c5e3a1ad05b4abe005d8711aad2083fd588af2",
                        width: 320,
                        height: 87,
                      },
                      {
                        url: "https://preview.redd.it/c5r01v03co7a1.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=c2e39f0940294f677b9a5ccac333343226db8db0",
                        width: 640,
                        height: 175,
                      },
                    ],
                    variants: {},
                    id: "rK39jCKrU8SzE2-yXqSLwB1W9BUV524ylXWJwlP5-xQ",
                  },
                ],
                enabled: true,
              },
              all_awardings: [],
              awarders: [],
              media_only: false,
              link_flair_template_id: "fe277d42-440f-11e8-8ec3-0eac434afc94",
              can_gild: false,
              spoiler: false,
              locked: false,
              author_flair_text: ":py:",
              treatment_tags: [],
              visited: false,
              removed_by: null,
              mod_note: null,
              distinguished: null,
              subreddit_id: "t5_2tex6",
              author_is_blocked: false,
              mod_reason_by: null,
              num_reports: null,
              removal_reason: null,
              link_flair_background_color: "#373c3f",
              id: "ztlduy",
              is_robot_indexable: true,
              report_reasons: null,
              author: "Mys7eri0",
              discussion_type: null,
              num_comments: 1186,
              send_replies: false,
              whitelist_status: "all_ads",
              contest_mode: false,
              mod_reports: [],
              author_patreon_flair: false,
              author_flair_text_color: "dark",
              permalink:
                "/r/ProgrammerHumor/comments/ztlduy/python_programmers_be_like_yeah_that_makes_sense/",
              parent_whitelist_status: "all_ads",
              stickied: false,
              url: "https://i.redd.it/c5r01v03co7a1.jpg",
              subreddit_subscribers: 3154052,
              created_utc: 1671812796.0,
              num_crossposts: 2,
              media: null,
              is_video: false,
            },
          },
        ],
        before: null,
      },
    },
    github: [],
    wikipedia: [],
  },
};

export default data;